# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Quality Checks
concurrency: Quality-Checks-${{ github.ref }}
on:
  pull_request:
jobs:
  quality-checks:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
      - name: Cache Pre-commit
        uses: actions/cache@v3.0.6
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/jsonschema_validate
            ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('**/.pre-commit-config.yaml') }}
      - name: Pre-commit
        uses: pre-commit/action@v2.0.3
      - name: CODEOWNERS validator
        uses: mszostok/codeowners-validator@v0.7.3
        with:
          checks: files,duppatterns,syntax
          experimental_checks: notowned
          github_access_token: ${{ secrets.GH_PAT_RO }}
